#!/bin/sh

/bin/mount -t devtmpfs none /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

unlocked=1
while [ $unlocked -ne 1 ]; do
    disks=$(/usr/sbin/sedutil-cli --scan | /usr/bin/awk '$1 ~ /^\/dev/ && $2 ~ /2/ { print $1 }')
    # TODO
#     for disk in /dev/nvme?n?; do
#         echo -n 'Password: '
#         read -r -s password
#     done
done

/sbin/reboot -f
