#!/bin/sh

/bin/mount -t devtmpfs none /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

# locked=1
# disks=$(/usr/sbin/sedutil-cli --scan | /usr/bin/awk '/^\/dev/ { print $1 }')
# while [ $locked -ne 0 ]; do
#     for disk in /dev/nvme?n?; do
#         echo -n 'Password: '
#         read -r -s password
#     done
# done

exec /bin/sh
